# Generated by Django 4.0.2 on 2022-05-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.TextField()),
                ('program_id', models.IntegerField()),
                ('completed_by_coordinator', models.BooleanField(default=False)),
                ('completed_by_supervisor', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(default=0)),
                ('form_num', models.IntegerField(default=0)),
                ('anythinh', models.IntegerField(default=0)),
            ],
        ),
    ]
