# Generated by Django 4.0.2 on 2022-05-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='anythinh',
            field=models.IntegerField(default=0, null=0),
        ),
    ]
