# Generated by Django 4.0.2 on 2022-05-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_forms_anythinh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='anythinh',
        ),
    ]
