# Generated by Django 4.0.2 on 2022-05-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_forms_anythinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='anything',
            field=models.IntegerField(default=0),
        ),
    ]
