# Generated by Django 4.0.2 on 2022-05-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_forms_anything'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='anything',
        ),
    ]
