# Generated by Django 4.0.2 on 2022-05-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField()),
                ('program_id', models.IntegerField()),
                ('supervisor_id', models.IntegerField()),
            ],
        ),
    ]
