# Generated by Django 4.0.2 on 2022-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='supervisor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
